apiVersion: v1

kind: Service

metadata:
  name: pneumonia-service

spec:

  selector:
    app: pneumonia-app

  type: NodePort

  ports:

  - protocol: TCP

    port: 5000

    targetPort: 5000

    nodePort: 30007